### ISSUE TITLE
如何更新数据源并刷新数据

### ISSUE THREAD

**Issue by afskalsfk** [NRatel/Unity-ListView#2]
如题，我展示了20条数据，我现在想切换另外20调数据并刷新   我重新调用了startview方法  但是页面没刷新

**Comment by afskalsfk** [comment]
现在处理方法是赋值个数为0 清空一下 然后再调用starview方法

**Comment by NRatel** [comment]
已解决，增加了一些实用的公有方法。
若数量变化，重新调用 StartShow，
若数量未变，调用 RefreshAll

**Comment by NRatel** [comment]
已解决，增加了一些实用的公有方法。
若数量变化，重新调用 StartShow，
若数量未变，调用 RefreshAll
